In [51]:
import pandas as pd
from google.cloud import aiplatform, bigquery
from google.cloud.aiplatform import gapic as aip_gapic

REGION = "us-central1"
PROJECT_ID = "planar-pagoda-425919-f0"
SERVICE_ACCOUNT = "475961067334-compute@developer.gserviceaccount.com"
BUCKET_NAME = "mlops-planar-pagoda-425919-f0-unique"
BUCKET_URI = "gs://mlops-planar-pagoda-425919-f0-unique"
MODEL_ENDPOINT = (
    "projects/475961067334/locations/us-central1/endpoints/2055029013755199488"
)
MODEL_NAME = "ml-antiscam"
DATASET_ID = "ml"
VALIDATE_TABLE_ID = "antiscam_val"

aiplatform.init(project=PROJECT_ID, location="us-central1")

In [64]:
bq_client = bigquery.Client(project=PROJECT_ID)

query = f"""
SELECT *
FROM `{PROJECT_ID}.{DATASET_ID}.{VALIDATE_TABLE_ID}`
LIMIT 100
"""
df = bq_client.query(query).to_dataframe()

I0000 00:00:1721462484.425065  416590 work_stealing_thread_pool.cc:320] WorkStealingThreadPoolImpl::PrepareFork
/opt/homebrew/Caskroom/miniconda/base/envs/ucu-linear-algebra/lib/python3.10/site-packages/google/cloud/bigquery/table.py:1727: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

,is_scam,daily_number_spends,total_number_spends,daily_credits_changed,total_credits_changed,daily_virtual_gifts_number_spends,total_virtual_gifts_number_spends,daily_virtual_gifts_credits_changed,total_virtual_gifts_credits_changed,daily_messages_number_spends,...,daily_number_orders,daily_amount,total_7d_number_orders,total_number_orders,total_7d_amount,total_amount,daily_number_requests,total_7d_number_requests,total_30d_number_requests,total_number_requests
31,True,35,221,193,2044,1.0,3.0,89.0,1218.0,28.0,...,3,649.97,17,573,1399.83,61820.86,1.0,8.0,24.0,24.0

In [65]:
df[df["is_scam"] == True]

,is_scam,daily_number_spends,total_number_spends,daily_credits_changed,total_credits_changed,daily_virtual_gifts_number_spends,total_virtual_gifts_number_spends,daily_virtual_gifts_credits_changed,total_virtual_gifts_credits_changed,daily_messages_number_spends,...,daily_number_orders,daily_amount,total_7d_number_orders,total_number_orders,total_7d_amount,total_amount,daily_number_requests,total_7d_number_requests,total_30d_number_requests,total_number_requests
12,True,37,830,4924,8099,3.0,11.0,4800.0,5850.0,30.0,...,7,1249.93,21,139,1679.79,5331.61,2.0,4.0,4.0,4.0
13,True,91,10688,1082,77029,2.0,215.0,800.0,44611.0,86.0,...,4,299.96,27,632,5539.73,33797.61,3.0,12.0,23.0,23.0
14,True,1,1421,50,5595,0.0,0.0,0.0,0.0,0.0,...,5,2499.95,35,659,15399.65,123351.93,1.0,1.0,1.0,1.0
31,True,35,221,193,2044,1.0,3.0,89.0,1218.0,28.0,...,3,649.97,17,573,1399.83,61820.86,1.0,8.0,24.0,24.0
32,True,21,179,5038,5378,2.0,2.0,5000.0,5000.0,19.0,...,6,1398.91,16,21,1648.44,1738.55,2.0,2.0,2.0,2.0
33,True,78,967,5196,18828,2.0,9.0,5000.0,13697.0,75.0,...,3,1199.97,13,19,4399.87,4872.81,1.0,1.0,1.0,1.0
34,True,2,754,4,3249,0.0,0.0,0.0,0.0,2.0,...,1,499.99,10,135,1529.90,21177.60,1.0,12.0,25.0,25.0
35,True,70,1825,828,34739,0.0,0.0,0.0,0.0,49.0,...,1,499.99,21,63,9599.79,26802.37,0.0,0.0,0.0,0.0
41,True,158,1810,9609,35681,3.0,11.0,8107.0,17895.0,69.0,...,7,2299.93,31,323,8599.69,131189.77,1.0,13.0,21.0,21.0
46,True,100,685,5526,14673,1.0,30.0,5000.0,11159.0,78.0,...,3,1199.97,20,32,6099.80,8302.68,1.0,1.0,1.0,1.0

In [74]:
endpoint = aiplatform.Endpoint(endpoint_name=MODEL_ENDPOINT)
instance = list(df.iloc[12:46, 1:].astype(float).values.tolist())
response = endpoint.predict(instance)
print("API response: ", response)

I0000 00:00:1721463856.414701  416590 check_gcp_environment_no_op.cc:29] ALTS: Platforms other than Linux and Windows are not supported
I0000 00:00:1721463856.416028  416590 check_gcp_environment_no_op.cc:29] ALTS: Platforms other than Linux and Windows are not supported
I0000 00:00:1721463856.734950  511545 subchannel.cc:806] subchannel 0x12eaae7f0 {address=ipv6:%5B2a00:1450:401b:80d::200a%5D:443, args={grpc.client_channel_factory=0x6000021c29e0, grpc.default_authority=us-central1-aiplatform.googleapis.com:443, grpc.dns_enable_srv_queries=1, grpc.http2_scheme=https, grpc.internal.channel_credentials=0x6000023442a0, grpc.internal.client_channel_call_destination=0x1232ea718, grpc.internal.event_engine=0x600002174ae0, grpc.internal.security_connector=0x600000dad180, grpc.internal.subchannel_pool=0x6000008cda40, grpc.max_receive_message_length=-1, grpc.max_send_message_length=-1, grpc.primary_user_agent=grpc-python/1.65.1, grpc.resource_quota=0x600002c2c630, grpc.server_uri=dns:///us-central1-aiplatform.googleapis.com:443}}: connect failed (UNKNOWN:connect: No route to host (65) {created_time:"2024-07-20T11:24:16.734588+03:00"}), backing off for 1000 ms

API response:  Prediction(predictions=[1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 1.0, 0.0, 0.0], deployed_model_id='4532926901018165248', metadata=None, model_version_id='3', model_resource_name='projects/475961067334/locations/us-central1/models/ml-antiscam', explanations=None)